"""
Render the authored meshes to PNG so they can actually be looked at.

    blender --background --factory-startup --python tools/blender/render_preview.py \
        -- --module build_table --out work/model-preview

Why this exists: every model in this project is generated by a script, and a
script is exactly the kind of thing that produces a chip which is arithmetically
perfect and reads as a bright green nub. The game captures catch that eventually,
but only at the end of a package-and-audit cycle, and only at the size and angle
the table happens to show. This puts each mesh on its own, big, from three
angles, in seconds.

Cycles on the CPU at low sample counts, deliberately: EEVEE and Workbench both
want a GL context, which a headless Windows session does not reliably have, and
a preview that only renders on some machines is worse than none. Twenty-four
samples of a handful of small meshes is a few seconds and the noise is invisible
at this scale.

The lighting is a neutral three-point studio setup rather than a copy of the
game's. The game's pendant is a deliberately dramatic single key, which is
excellent for atmosphere and terrible for judging whether a shape is right --
half the model disappears. Shape first here; the in-game captures remain the
place to judge how it reads under the real light.
"""
import argparse
import importlib
import math
import os
import sys

import bpy
import mathutils


RESOLUTION = 640
SAMPLES = 24


def clear_scene():
    bpy.ops.wm.read_factory_settings(use_empty=True)


def configure_render(out_path):
    scene = bpy.context.scene
    scene.render.engine = "CYCLES"
    scene.cycles.device = "CPU"
    scene.cycles.samples = SAMPLES
    scene.cycles.use_denoising = False
    scene.render.resolution_x = RESOLUTION
    scene.render.resolution_y = RESOLUTION
    scene.render.resolution_percentage = 100
    scene.render.film_transparent = False
    scene.render.filepath = out_path
    scene.render.image_settings.file_format = "PNG"
    world = bpy.data.worlds.new("preview")
    world.use_nodes = True
    world.node_tree.nodes["Background"].inputs[0].default_value = (0.06, 0.06, 0.07, 1.0)
    world.node_tree.nodes["Background"].inputs[1].default_value = 1.0
    scene.world = world


def add_sun(name, direction, strength):
    """
    Suns, not area lights.

    A point or area light's irradiance depends on its distance, so lighting a
    4 cm chip and a 2.3 m table the same way means solving an inverse-square
    every time the subject changes size -- and getting it wrong renders the chip
    almost black, which is what the first pass did. A sun is defined by
    direction and strength alone, so one rig lights every subject identically at
    any scale.
    """
    data = bpy.data.lights.new(name, type="SUN")
    data.energy = strength
    data.angle = math.radians(12.0)
    light = bpy.data.objects.new(name, data)
    bpy.context.collection.objects.link(light)
    light.rotation_mode = "QUATERNION"
    light.rotation_quaternion = mathutils.Vector(direction).to_track_quat("-Z", "Y")
    return light


def studio_lights(_radius):
    add_sun("key", (-0.55, 0.60, -0.85), 3.2)
    add_sun("fill", (0.70, 0.45, -0.35), 1.1)
    add_sun("rim", (0.10, -0.90, -0.35), 2.0)


def neutral_material():
    material = bpy.data.materials.new("preview")
    material.use_nodes = True
    bsdf = material.node_tree.nodes["Principled BSDF"]
    bsdf.inputs["Base Color"].default_value = (0.62, 0.60, 0.58, 1.0)
    bsdf.inputs["Roughness"].default_value = 0.55
    if "Specular" in bsdf.inputs:
        bsdf.inputs["Specular"].default_value = 0.25
    return material


def bounds_of(objects):
    lo = mathutils.Vector((1e9, 1e9, 1e9))
    hi = mathutils.Vector((-1e9, -1e9, -1e9))
    for obj in objects:
        for corner in obj.bound_box:
            point = obj.matrix_world @ mathutils.Vector(corner)
            for axis in range(3):
                lo[axis] = min(lo[axis], point[axis])
                hi[axis] = max(hi[axis], point[axis])
    return lo, hi


def frame_camera(objects, azimuth, elevation):
    lo, hi = bounds_of(objects)
    centre = (lo + hi) / 2.0
    radius = max((hi - lo).length / 2.0, 1e-4)

    data = bpy.data.cameras.new("camera")
    data.lens = 60.0
    camera = bpy.data.objects.new("camera", data)
    bpy.context.collection.objects.link(camera)
    bpy.context.scene.camera = camera

    # Fit the subject to the frame rather than guessing a multiple of its size.
    # At a 60 mm lens the half-angle is 16.7 degrees, so a 3.1x distance framed a
    # circle smaller than the subject and cropped every render.
    half_fov = math.atan(0.5 * data.sensor_width / data.lens)
    distance = radius / math.tan(half_fov) * 1.35
    camera.location = (
        centre.x + math.cos(elevation) * math.sin(azimuth) * distance,
        centre.y - math.cos(elevation) * math.cos(azimuth) * distance,
        centre.z + math.sin(elevation) * distance,
    )
    camera.rotation_mode = "QUATERNION"
    camera.rotation_quaternion = (centre - mathutils.Vector(camera.location)).to_track_quat("-Z", "Y")
    return radius


def render_object(builder, name, out_dir, views):
    """Build one mesh on an empty scene and render it from `views` angles."""
    for index, (azimuth, elevation) in enumerate(views):
        clear_scene()
        objects = builder()
        material = neutral_material()
        for obj in objects:
            obj.data.materials.append(material)
        radius = frame_camera(objects, azimuth, elevation)
        studio_lights(radius)
        safe = name.replace("/", "-")
        configure_render(os.path.join(out_dir, "%s-%d.png" % (safe, index)))
        bpy.ops.render.render(write_still=True)
        print("RENDERED", safe, index)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--module", default="build_table")
    parser.add_argument("--out", required=True)
    parser.add_argument("--only", default="")
    argv = sys.argv[sys.argv.index("--") + 1:] if "--" in sys.argv else []
    args = parser.parse_args(argv)

    sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
    module = importlib.import_module(args.module)
    out_dir = os.path.abspath(args.out)
    os.makedirs(out_dir, exist_ok=True)

    wanted = [name for name in args.only.split(",") if name]
    views = [
        (math.radians(35.0), math.radians(28.0)),
        (math.radians(-70.0), math.radians(14.0)),
        (math.radians(0.0), math.radians(72.0)),
    ]

    for name, builder in module.preview_subjects().items():
        if wanted and name not in wanted:
            continue
        render_object(builder, name, out_dir, views)


if __name__ == "__main__":
    main()
